[package]

name = "svg_shape_utils"
version = "0.0.1"
description = "Helper for several often used svg shapes."
authors = ["Mark Benedikt Boss <markboss@mailbox.org>"]
license = "MIT/Apache-2.0"

[lib]
name = "svg_shape_utils"
path = "src/lib.rs"

[dependencies]
svg = "0.5.10"